### PR TITLE
Added WC 0.8mm drill with thinner pad.

### PR DESCRIPTION
**Pull request by crackerizer**

### CODE REVIEW

**Comment by CarlPoirier** [comment]
Hi,

The footprint anchor has not been properly set. I'm not sure what happened but your commit doesn't contain the change. While you're at it, would you mind setting it for the other footprints in the same library?

Thanks,

Carl

**Comment by crackerizer** [comment]
Hello Carl,

I have moved all the library's anchors to pin 1 including modify REF & value of the module I added.

**Comment by ricardocrudo** [comment]
Could you please add some description to the footprints?

**Comment by crackerizer** [comment]
Done.

**Comment by ricardocrudo** [comment]
Thank you.

**Pull request merged**
