### PR TITLE
add SMD Pad footprints 0.8-2.5mm

### PR DESCRIPTION
**Pull request by jstjst**

### CODE REVIEW

**Comment by ashtonchase** [comment]
Hi @jstjst , 
Please update the footprints to correct KLC Violations Rules 10.4 10.5 and 6.4 for all additions
I think for these you can ignore Rule 6.6

You can use the [kicad-library-utils](https://github.com/KiCad/kicad-library-utils) to automatically fix these errors. 
Specifically using  **kicad-library-utils/pcb/check_kicad_mod.py**

[KiCAD Library Conventions](https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention)

**Comment by evanshultz** [comment]
@SchrodingersGat @jkriege2 
It appears these footprints are in the Wire_Connections.pretty library. If so, can this PR be closed? If not, what needs to be done to this PR?

**Comment by SchrodingersGat** [comment]
This entire repo seems like it should be deprecated and just [Wire Pads](https://github.com/KiCad/Wire_Pads.pretty) repo used...

**Comment by evanshultz** [comment]
@SchrodingersGat @jkriege2 @poeschlr @pointhi 
I second that. Any objections?

**Comment by evanshultz** [comment]
To all librarians: Any reason not to deprecate this repo?

**Comment by poeschlr** [comment]
I can't find any reason why it should not be deprecated.

**Comment by SchrodingersGat** [comment]
This repo is now marked as deprecated

**Pull request closed without merging**
